@IssueTrackerApi_HostAddress = http://localhost:1337


GET {{IssueTrackerApi_HostAddress}}/status


### Get the Status

GET {{IssueTrackerApi_HostAddress}}/status/support
### Adding an Issue

POST {{IssueTrackerApi_HostAddress}}/issues
Content-Type: application/json

{
  "Software": "Destiny 2",
  "description": "Keep getting insta-killed in crucible",
  "impact": "Inconvenience"
  
}


### Get My Issue

GET {{IssueTrackerApi_HostAddress}}/issues